### PR TITLE
feat: add support for Gemini, Claude through Langchain

### LINKED ISSUE #204: Add support for Anthropic
### Reference Issues

Given how influential Claude has become, it would be good to have support for Claude as well. 

### Summary

User will be able to select Claude as a possible model for the AI

### Basic Example

As above

### Drawbacks

Added Code-base complexity

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by taprosoft**
## Description

- Add support for Gemini, Claude through Langchain wrapper
- Add default model template for Gemini, Claude, Groq
- Fix #204, #160

## Type of change

- [x] New features (non-breaking change).
- [ ] Bug fix (non-breaking change).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added thorough tests if it is a core feature.
- [ ] There is a reference to the original bug report and related work.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] The feature is well documented.

### CODE REVIEW

**Comment by eddprogrammer** [comment]
I am getting connection error after adding the API Key and Model Name in the configuration and testing the connection. I have tested and confirmed the API key and Model name are correct.

**Comment by cin-jimmy** [comment]
@eddprogrammer can you provide more details or even attach a logs.txt for further investigation. Thanks

**Comment by eddprogrammer** [comment]
> logs.txt

Jimmy, sorry about the dump question - where can I find the log file? I am on Windows 10.

**Comment by cin-jimmy** [comment]
@eddprogrammer If you're installing on Hugging Face, find the "logs" in the 3 dots 
image

Otherwise, you can check the terminal windows. You can either screenshot the logs on the terminal or copy and paste it to a .txt file.

**Comment by eddprogrammer** [comment]
Thanks Jimmy - see screenshot below from both UI and the Terminal. There is not much info on the terminal window though. 
image

image

**Pull request merged**
