### PR TITLE
fix: update parsing llm_output for citation

### PR DESCRIPTION
**Pull request by khankaholic**

### CODE REVIEW

**Comment by lone17** [comment]
@cin-kay do you have an example where citation works ? I couldn't find any to test this.

**Comment by khankaholic** [comment]
> @cin-kay do you have an example where citation works ? I couldn't find any to test this.

a @lone17, I believe you need to enable citation fist by set this to `True`, it's off by default. Secondly, in case of having LLM citation answer but highlight markdown citation then maybe you need change the LLM model of citation to GPT-4 to ensure the quote text match with evidence.

https://github.com/Cinnamon/kotaemon/blob/56dfc8fb53965f3000c00a3f0e2449ac8363d875/libs/ktem/ktem/reasoning/simple.py#L735-L739

You can try with this file about `how car works` with a simple question `xe hơi dùng để làm gì?`
[sample1.txt](https://github.com/Cinnamon/kotaemon/files/15431765/sample1.txt)

**Comment by khankaholic** [comment]
a @lone17 Btw, I just tried to launch the app again but it takes too long to get start.

**Comment by khankaholic** [comment]
I'm closing this one since the root cause may be due to timeout, not the interface of the LLM output.

**Comment by lone17** [comment]
@cin-kay I thought without this fix there is an error when citation is enabled ?

**Comment by khankaholic** [comment]
@lone17 Have you tried again by enabling citation and increasing the timeout on the main branch?
Yesterday, I was able to use it without any errors.

**Comment by lone17** [comment]
@cin-kay what amount of timeout should I set to ?

**Pull request closed without merging**
