### PR TITLE
fix: one-click installers (bump:patch)

### PR DESCRIPTION
**Pull request by cin-albert**
## Description

- Fix a few issues of non-dev installers for Windows and Linux by reviewing and adding missing dependencies.
- Issue #133 

## Type of change

- [ ] New features (non-breaking change).
- [x] Bug fix (non-breaking change).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added thorough tests if it is a core feature.
- [ ] There is a reference to the original bug report and related work.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] The feature is well documented.

### CODE REVIEW

**Comment by Tambajoyce** [comment]
okay thank you very much. but please can you clarify me more on what you want me to do?

**Comment by phv2312** [comment]
Thanks @cin-albert . I check and it seems can work on my Ubuntu.

**Comment by phv2312** [comment]
Works on my window machine too

**Review by phv2312 — APPROVED** [review]
LGTM

**Pull request merged**
