### PR TITLE
fix: fix Application UI using UTC time

### LINKED ISSUE #262: [BUG] Minor bug: Application UI time using UTF time instead of system time
### Description

as described.

image

### Reproduction steps

```bash
Launched from windows, following non-docker guide for setting up the app. I don't think it matter which platform you are using though.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

Chrome

### OS

Windows

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cin-cris**
## Description

- Before, the time in the name of new conversation is follow UTC+0 no matter where user is. So I use tzlocal library to get the local machine's time to change in the name.
- Fixes #262

## Type of change

- [ ] New features (non-breaking change).
- [X] Bug fix (non-breaking change).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).

## Checklist

- [X] I have performed a self-review of my code.
- [X] I have added thorough tests if it is a core feature.
- [X] There is a reference to the original bug report and related work.
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] The feature is well documented.

### CODE REVIEW

**Comment by taprosoft** [comment]
@cin-cris please also update the `date_created` field on various place https://github.com/search?q=repo%3ACinnamon%2Fkotaemon%20date_created&type=code

Notably
[libs/ktem/ktem/db/base_models.py](https://github.com/Cinnamon/kotaemon/blob/908452cc187b1ff0440f1865071e1192ce13825f/libs/ktem/ktem/db/base_models.py#L40)
[libs/ktem/ktem/index/file/index.py](https://github.com/Cinnamon/kotaemon/blob/908452cc187b1ff0440f1865071e1192ce13825f/libs/ktem/ktem/index/file/index.py#L75)

**Comment by cin-cris** [comment]
@taprosoft I updated the `date_created` and other time-related field all over the repo. Please review again.

**Comment by taprosoft** [comment]
Still missing `date_created` for uploaded file
https://github.com/Cinnamon/kotaemon/blob/908452cc187b1ff0440f1865071e1192ce13825f/libs/ktem/ktem/index/file/index.py#L75

**Comment by cin-cris** [comment]
@taprosoft done changing all `date_created` field. Please kindly review.

**Review by taprosoft — APPROVED** [review]
LGTM

**Comment by taprosoft** [comment]
@cin-cris Thanks for your contribution.

**Pull request merged**
